root: true

env:
  es6: true
  browser: true
  node: true

extends:
 - "airbnb-base"
 - "plugin:prettier/recommended"

plugins:
  - "babel"
  - "import"
  - "plugin:prettier"

parser: "babel-eslint"

parserOptions: 
    ecmaVersion: 6
    sourceType: "module"

rules: 
  no-console: "off"
  prettier/prettier: "error"